### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by larshp** [pawelwiejkut/bw_trfn_framework#2]
Hi,
What is the license for this code? If you add a license, then I'll add your project to [dotabap.org](https://dotabap.org)

See
https://help.github.com/articles/adding-a-license-to-a-repository/
https://choosealicense.com/

**Comment by larshp** [comment]
same for https://github.com/pawelwiejkut/bw_toolbox

**Comment by pawelwiejkut** [comment]
Hello, licenses updated. Thank you for support !
